name: TestPlugin
version: '${version}'
main: ru.zako.testplugin.TestPlugin
author: ["Zako", ""]
api-version: '1.16'
commands:
  giveitem:

  getdbuser:

  setuserage:

  firstcommand:
    description: Просто команда
    name: firstcommand
    aliases:
      - fs
    permission: testplugin.fc
    permission-message: Нет прав
    usage: /firstcommand [arg1] [arg2]